config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#welcome'

  devise_for :job_seekers, controllers: {
    registrations: 'job_seekers/registrations'
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }

  resources :home do
    member do
      post 'apply'
    end
  end
  resources :job_seekers, only: %i[edit update destroy show] do
    member do
      get 'applys'
    end
  end

  resources :jobs do
    member do
      get :applyers
      get 'applyer/:job_seeker_id', to: 'jobs#applyer', as: :applyer
    end
  end
  resources :employers

  devise_scope :job_seeker do
    get '/job_seekers/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :employer do
    get '/employers/sign_out' => 'devise/sessions#destroy'
  end

  get 'start', to: 'home#index', as: :start
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/job_seeker.rb
# frozen_string_literal: true

class JobSeeker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :profile_img

  validate :correct_profile_img_mime_type

  has_many :applications, dependent: :destroy
  has_many :jobs, through: :applications

  private

  def correct_profile_img_mime_type
    if profile_img.attached? && !profile_img.content_type.in?(%w[image/jpeg image/png image/gif])
      errors.add(:profile_img, 'deve ser uma imagem JPG, PNG ou GIF')
    elsif profile_img.attached? && profile_img.byte_size > 5.megabytes
      errors.add(:profile_img, 'deve ser menor que 5MB')
    end
  end
end

app/controllers/job_seekers/registrations_controller.rb
# frozen_string_literal: true

class JobSeekers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |job_seeker|
      if job_seeker.persisted?
        sign_in(job_seeker)
        redirect_to start_path
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super do |job_seeker|
      if job_seeker.destroyed?
        redirect_to root_path, notice: 'Sua conta foi excluida com sucesso. Você foi redirecionado para a pagina inicial'
        return
      end
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/job_seekers_controller.rb
class JobSeekersController < ApplicationController
  before_action :authenticate_job_seeker!
  before_action :set_job_seeker, only: %i[show edit update destroy]

  def applys
    @applications = current_job_seeker.jobs
  end

  def show; end

  def edit; end

  def update
    if @job_seeker.update(job_seeker_params)
      redirect_to job_seeker_url(@job_seeker), notice: 'Perfil atualizado com sucesso'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job_seeker.destroy
    redirect_to root_url
  end

  private

  def set_job_seeker
    @job_seeker = current_job_seeker
  end

  def job_seeker_params
    params.require(:job_seeker).permit(%i[full_name phone email degree courses experiences profile_img])
  end
end

app/helpers/job_seekers_helper.rb
# frozen_string_literal: true

module JobSeekersHelper
end

app/views/job_seekers/_form.html.erb
<%= form_with(model: @job_seeker, local: true, class: "space-y-6") do |form| %>

  <div class="flex flex-col">
    <%= form.label :profile_img, "Foto de Perfil", class: "text-gray-700 font-bold mb-2" %>
    <%= form.file_field :profile_img, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600 cursor-pointer bg-white" %>
  </div>

  <div class="flex flex-col">
    <%= form.label :full_name, "Nome Completo", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :full_name, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :email, "Email", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :email, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>
  
  <div class="flex flex-col">
    <%= form.label :phone, "Telefone", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :phone, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :degree, "Escolaridade", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_area :degree, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :courses, "Cursos e Certificações", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_area :courses, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :experiences, "Experiências", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_area :experiences, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="text-center">
    <%= form.submit 'Editar Perfil', class: "bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-md font-bold cursor-pointer" %>
  </div>

<% end %>

app/views/job_seekers/_header.html.erb
<header class="bg-white shadow-lg w-full fixed top-0 left-0 z-40">
    <div class="w-11/12 mx-auto px-4 sm:px-6 lg:px-8">
      <nav class="flex items-center justify-between h-20 sm:h-24 xl:h-24 relative" data-controller="mobile-menu">

        <div class="flex-shrink-0 text-2xl sm:text-3xl xl:text-4xl font-extrabold text-green-600">
          <%= link_to 'Feira Vagas', start_path %>
        </div>

        <div class="lg:flex lg:items-center lg:space-x-4 hidden md:hidden">
          <div class="text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold">
            <%= first_link %>
          </div>

          <div class="text-red-600 hover:bg-red-200 px-4 py-2 rounded-md text-md font-bold">
            <%= second_link  %>
          </div>
        </div>

        <button data-action="click->mobile-menu#toggle" aria-label="Menu" class="block lg:hidden px-2 py-1 text-green-700 hover:bg-green-100 rounded-md">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>

        <div data-mobile-menu-target="menu" class="lg:hidden fixed inset-0 bg-white z-50 hidden transition-transform transform duration-300 ease-in-out">
          <div class="flex flex-col items-end px-4 py-8">
            <button data-action="click->mobile-menu#toggle" aria-label="Fechar Menu" class="self-end px-4 py-2 text-gray-700">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>

            <div class="flex flex-col items-end px-4"> 
              
              <div class="text-green-700 hover:bg-green-100 px-2 py-2 rounded-md text-md font-bold">
                <%= first_link %>
              </div>

              <div class="text-red-700 hover:bg-red-100 px-2 py-2 rounded-md text-md font-bold">
                <%= second_link  %>
              </div>

            </div>
          </div>
        </div>
      </nav>
    </div>
</header>

app/views/job_seekers/_job.html.erb
<div id="<%= dom_id(job) %>" class="transition-transform transform hover:scale-105">
  <!-- Job Header -->
  <div class="flex flex-row justify-between items-center mb-4">
    <p class="text-lg font-semibold text-green-700"><%= job.employer.company_name %></p>
    <p class="text-sm text-gray-500"><%= job.created_at.strftime('%d/%m') %></p>
  </div>
  
  <!-- Job Title -->
  <div class="mb-4">
    <h2 class="text-xl font-bold text-gray-800"><%= job.title %></h2>
  </div>

  <!-- Job Details -->
  <div class="flex flex-col text-gray-600">
    <p class="mb-1"><strong>Localização:</strong> <%= job.location %></p>
    <p><strong>Modalidade:</strong> <%= job.mode %></p>
  </div>
</div>

app/views/job_seekers/_job_seeker_data.html.erb
<div class="flex flex-col items-center space-y-6">
  <div class="w-52 h-52 rounded-full bg-gray-200 flex items-center justify-center">
    <% if @job_seeker.profile_img.attached? %>
      <%= image_tag @job_seeker.profile_img, alt: "Foto de Perfil", class: "rounded-full object-cover w-full h-full" %>
    <% else %>
      <p>No image</p>
    <% end %>
  </div>

  <div class="text-center">
    <h2 class="text-2xl font-bold text-gray-800"><%= @job_seeker.full_name %></h2>
    <p class="text-gray-500"><%= @job_seeker.email %></p>
    <p class="text-gray-500"><%= @job_seeker.phone %></p>
  </div>

  <div class="w-full text-left mt-8 space-y-4">
    <div>
      <h3 class="text-lg font-bold text-gray-700">Formação Acadêmica</h3>
      <p class="text-gray-600 whitespace-pre-wrap"><%= @job_seeker.degree %></p>
    </div>

    <div>
      <h3 class="text-lg font-bold text-gray-700">Cursos</h3>
      <p class="text-gray-600 whitespace-pre-wrap"><%= @job_seeker.courses %></p>
    </div>
    
    <div>
      <h3 class="text-lg font-bold text-gray-700">Experiências</h3>
      <p class="text-gray-600 whitespace-pre-wrap"><%= @job_seeker.experiences %></p>
    </div>
  </div>
</div>

app/views/job_seekers/applys.html.erb
<div class="container flex flex-col mx-auto items-center justify-center min-h-screen py-8">
  <%= render 'header',
              first_link: link_to('Meu Perfil', job_seeker_path, class: "text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold"),
              second_link: button_to('Sair', destroy_job_seeker_session_path, method: :delete, class: "text-red-600 hover:bg-red-200 px-4 rounded-md text-md font-bold") %>
  <h1 class="text-2xl font-bold text-green-600">Minhas Candidaturas</h1>

  <main class="w-11/12 xl:w-full lg:px-8 mt-24 mx-auto grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">

    <% @applications.each do |applications| %>
      <%= link_to home_path(applications), class: "md:transform md:hover:scale-105 transition-transform duration-200 ease-in-out" do %>
        <div class="bg-white overflow-hidden shadow-lg rounded-lg p-6">
          <%= render 'job', job: applications %>
        </div>
      <% end %>
    <% end %>
  </main>
</div>

app/views/job_seekers/edit.html.erb
<div class="container flex flex-col mx-auto items-center justify-center min-h-screen py-8">
  <%= render 'header',
              first_link: link_to('Meu Perfil', job_seeker_path, class: "text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold"),
              second_link: button_to('Sair', destroy_job_seeker_session_path, method: :delete, class: "text-red-600 hover:bg-red-200 px-4 rounded-md text-md font-bold") %>
  

  <div class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <%= render 'form', job_seeker: @job_seeker %>
  </div>

  <div class="mt-6 text-center">
    <%= link_to 'Ir para vagas', start_path, class: "text-green-600 hover:underline py-3 px-4 rounded-md text-md font-bold" %>
  </div>
</div>

app/views/job_seekers/show.html.erb
<div class="container flex flex-col mx-auto items-center justify-center min-h-screen py-8">
  <%= render 'header',
              first_link: link_to('Minhas Candidaturas', applys_job_seeker_path, class: "text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold"),
              second_link: button_to('Sair', destroy_job_seeker_session_path, method: :delete, class: "text-red-600 hover:bg-red-200 px-4 rounded-md text-md font-bold") %>

  <div class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <%= render 'job_seeker_data' %>

    <div class="mt-6 text-center flex flex-row justify-between">
      <%= link_to 'Editar Perfil', edit_job_seeker_path, class: "text-white bg-green-600 hover:bg-green-700 px-6 py-2 rounded-md font-bold" %>      
      <%= button_to 'Excluir Perfil', registration_path(current_job_seeker), method: :delete, class: "text-white bg-red-600 hover:bg-red-700 px-6 py-2 rounded-md font-bold" %>    
    </div>
  </div>
</div>