config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#welcome'

  devise_for :job_seekers, controllers: {
    registrations: 'job_seekers/registrations'
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }

  resources :home do
    member do
      post 'apply'
    end
  end
  resources :job_seekers, only: %i[edit update destroy show] do
    member do
      get 'applys'
    end
  end

  resources :jobs do
    member do
      get :applyers
      get 'applyer/:job_seeker_id', to: 'jobs#applyer', as: :applyer
    end
  end
  resources :employers

  devise_scope :job_seeker do
    get '/job_seekers/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :employer do
    get '/employers/sign_out' => 'devise/sessions#destroy'
  end

  get 'start', to: 'home#index', as: :start
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :employer

  validates_presence_of %i[title location mode description requirements skills benefits salary]

  has_many :applications, dependent: :destroy
  has_many :job_seekers, through: :applications
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy]
  before_action :set_applyers, only: %i[ applyers applyer ]
  before_action :authenticate_employer!
  before_action :verify_profile, only: %i[ create new ]

  def index
    jobs = current_employer.jobs
    @jobs = jobs.sort_by(&:created_at).reverse
  end

  def new
    @job = Job.new
  end

  def applyers; end
  
  def applyer
    @applyer = @applyers.find(params[:job_seeker_id])
  end
  
  def show; end

  def edit; end

  def create
    @job = current_employer.jobs.new(job_params)

    if @job.save
      redirect_to job_url(@job), notice: 'Vaga publicada com sucesso'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @job.update(job_params)
      redirect_to job_url(@job), notice: 'Vaga atualizada com sucesso'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_url, notice: 'A vaga foi excluída com sucesso.'
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end
  
  def set_applyers
    @job = Job.find(params[:id])
    @applyers = @job.job_seekers
  end
  
  def job_params
    params.require(:job).permit(:title, :description, :location, :mode, :salary, :requirements, :skills, :benefits)
  end
  
  def verify_profile
    if current_employer.company_name == nil
      redirect_to edit_employer_path(current_employer)
    end
  end
end

app/helpers/jobs_helper.rb
# frozen_string_literal: true

module JobsHelper
end

app/views/jobs/_applyer_data.html.erb
<div class="flex flex-col items-center space-y-6">
  <div class="w-52 h-52 rounded-full bg-gray-200 flex items-center justify-center">
    <% if @applyer.profile_img.attached? %>
      <%= image_tag @applyer.profile_img, alt: "Foto de Perfil", class: "rounded-full object-cover w-full h-full" %>
    <% else %>
      <p>No image</p>
    <% end %>
  </div>

  <div class="text-center">
    <h2 class="text-2xl font-bold text-gray-800"><%= @applyer.full_name %></h2>
    <p class="text-gray-500"><%= @applyer.email %></p>
    <p class="text-gray-500"><%= @applyer.phone %></p>
  </div>

  <div class="w-full text-left mt-8 space-y-4">
    <div>
      <h3 class="text-lg font-bold text-gray-700">Formação Acadêmica</h3>
      <p class="text-gray-600 whitespace-pre-wrap"><%= @applyer.degree %></p>
    </div>
    
    <div>
      <h3 class="text-lg font-bold text-gray-700">Cursos</h3>
      <p class="text-gray-600 whitespace-pre-wrap"><%= @applyer.courses %></p>
    </div>
    
    <div>
      <h3 class="text-lg font-bold text-gray-700">Experiências</h3>
      <p class="text-gray-600 whitespace-pre-wrap"><%= @applyer.experiences %></p>
    </div>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: @job, local: true, class: "space-y-6") do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation" class="bg-red-100 text-red-700 p-4 rounded-md">
      <h2 class="font-bold text-lg"><%= pluralize(job.errors.count, 'error') %> proibiram esta vaga de ser salva:</h2>
      <ul class="list-disc pl-6">
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :title, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :localização, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :location, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :tipo_de_contrato, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :mode, placeholder: 'Ex: CLT - Presencial.', class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :salário, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_field :salary, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :descrição_da_vaga, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :description, rows: 5, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :requisitos, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :requirements, rows: 5, placeholder: 'Ex: Experiência, habilidades, idade, etc...', class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :qualificações,class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :skills, rows: 5, placeholder: 'Ex: Formação, graduação, etc...', class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.label :benefícios, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :benefits, rows: 5, class: "mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-green-500 focus:border-green-500 sm:text-sm" %>
  </div>

  <div>
    <%= form.submit 'Publicar', class: "bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500" %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id(job) %>" class="transition-transform transform hover:scale-105">
  <!-- Job Header -->
  <div class="flex flex-row justify-between items-center mb-4">
    <p class="text-lg font-semibold text-green-700"><%= job.employer.company_name %></p>
    <p class="text-sm text-gray-500"><%= job.created_at.strftime('%d/%m') %></p>
  </div>
  
  <!-- Job Title -->
  <div class="mb-4">
    <h2 class="text-xl font-bold text-gray-800"><%= job.title %></h2>
  </div>

  <!-- Job Details -->
  <div class="flex flex-col text-gray-600">
    <p class="mb-1"><strong>Localização:</strong> <%= job.location %></p>
    <p class="mb-1"><strong>Modalidade:</strong> <%= job.mode %></p>
    <p><strong>Candidaturas:</strong> <%= job.applications.count %></p>
  </div>
</div>

app/views/jobs/_job_information.html.erb
<section class="mb-6">
  <h1 class="text-3xl font-bold text-gray-800">
    <%= @job.title %>
  </h1>
  <h2 class="text-xl text-gray-600 mt-2">
    <%= @job.employer.company_name %>
  </h2>
</section>


<section class="mb-8 grid grid-cols-1 lg:grid-cols-2 gap-6">
  <div class="space-y-4">
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Localização:</h3>
      <p class="text-gray-600"><%= @job.location %></p>
    </div>
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Salário:</h3>
      <p class="text-gray-600"><%= @job.salary %></p>
    </div>
  </div>
  <div class="space-y-4">
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Tipo de Contrato:</h3>
      <p class="text-gray-600"><%= @job.mode %></p>
    </div>
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Data de Publicação:</h3>
      <p class="text-gray-600"><%= @job.created_at.strftime('%d/%m') %></p>
    </div>
  </div>
</section>

<section>
  <div class="pb-4" >
    <h3 class="text-xl font-semibold text-gray-700">Descrição da Vaga</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%= @job.description %></p>
  </div>
  
  <div class="pb-4">
    <h3 class="text-xl font-semibold text-gray-700">Requisitos</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%=@job.requirements %></p>
  </div>

  <div class="pb-4">
    <h3 class="text-xl font-semibold text-gray-700">Qualificações</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%= @job.skills %></p>
  </div>

  <div class="pb-4">
    <h3 class="text-xl font-semibold text-gray-700">Benefícios</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%= @job.benefits %></p>
  </div>
</section>

app/views/jobs/applyer.html.erb
<div class="container mx-auto min-h-screen flex flex-col items-center justify-center">
  <%= render 'header',
            first_link: link_to('Meu Pefil', employer_path(current_employer)),
            second_link: button_to('Sair', destroy_employer_session_path, method: :delete) %>


  <div class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
      
      <%= render 'applyer_data' %>
  
      <div class="mt-6 text-center">
        <%= link_to 'Voltar para candidaturas', applyers_job_path, class: "text-white bg-green-600 hover:bg-green-700 px-6 py-2 rounded-md font-bold" %>
      </div>
    </div>

</div>

app/views/jobs/applyers.html.erb
<div class="container mx-auto min-h-screen flex flex-col items-center">
  <%= render 'header',
            first_link: link_to('Meu Perfil', employer_path(current_employer)),
            second_link: button_to('Sair', destroy_employer_session_path, method: :delete) %>
  
  
  <hero class="w-11/12 xl:w-full lg:px-8 mx-auto flex flex-col gap-20 mt-48 ">
    <h2 class="text-center text-2xl font-semibold text-green-600">Todas as candidaturas</h2>
     
    <section class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
      <% @applyers.each do |applyer| %>
        <%= link_to applyer_job_path(job_seeker_id: applyer.id) do %>
          <div class="p-4 flex flex-col gap-3 rounded-md bg-white shadow-md text-start">
            <h2 class="text-xl font-semibold text-gray-800"><%= applyer.full_name %></h2>
            <p class="text-gray-600 font-medium"><strong>Formação:</strong> <%= applyer.degree%></p>
            <p class="text-gray-600 font-medium"><strong>Email:</strong> <%= applyer.email %></p>
          </div>
        <% end %>
      <% end %>
    </section>
  </hero>
</div>

app/views/jobs/edit.html.erb
<div class="container mx-auto py-8 min-h-screen flex flex-col items-center justify-center">
  <%= render 'header',
          first_link: link_to('Nova Vaga', new_job_path),
          second_link: button_to('Sair', destroy_employer_session_path, method: :delete) %>

  <div class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
    <h2 class="text-center text-xl font-semibold text-gray-700">Editar Vaga</h2> 

    <%= render 'form', job: @job %>

    <div class="mt-6 text-center">
      <%= link_to 'Mostrar vaga', @job, class: 'text-green-600 bg-green-200 hover:bg-green-300  py-3 p-4 rounded-md text-md font-bold' %>
    </div>
  </div>

  <div class="mt-6 text-center">
    <%= link_to 'Voltar para vagas', jobs_path, class: "text-green-600 hover:underline  py-3 p-4 rounded-md text-md font-bold" %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class=" container flex flex-col items-center justify-center mx-auto min-h-screen py-8">
  <%= render 'header',
          first_link: link_to('Meu Perfil', employer_path(current_employer)),
          second_link: button_to('Sair', destroy_employer_session_path, method: :delete)%>


  <main class="w-11/12 xl:w-full lg:px-8 mx-auto mt-28">
      <% if notice.present? %>
        <span class="flex place-items-start">
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 text-center mx-auto font-medium rounded-lg inline-bloc" id="notice"><%= notice %></p>
        </span>
      <% end %>
      
      <aside class="flex items-end mb-16 justify-end ">
        <%= link_to 'Criar vaga', new_job_path, class: 'bg-green-500 hover:bg-green-600 text-white font-semibold p-3 rounded-md shadow-md'  %>
      </aside>

    <section class="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
      <% @jobs.each do |job| %>
        <%= link_to job_path(job), class: "md:transform md:hover:scale-105 transition-transform duration-200 ease-in-out" do %>
          <div class="bg-white overflow-hidden shadow-lg rounded-lg p-6">
            <%= render 'job', job: job %>
          </div>
        <% end %>
      <% end %>
    </section>
  </main>
</div>

app/views/jobs/new.html.erb
<div class="container mx-auto py-8 min-h-screen flex flex-col items-center justify-center">
  <%= render 'header',
          first_link: link_to('Nova Vaga', new_job_path),
          second_link: button_to('Sair', destroy_employer_session_path, method: :delete) %>

  <div class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
    <h2 class="text-center text-xl font-semibold text-gray-700">Nova Vaga</h2> 
    <%= render 'form', job: @job %>
  </div>

  <div class="mt-8 text-center">
    <%= link_to 'Voltar para vagas', jobs_path, class: "text-green-600 hover:underline" %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container mx-auto min-h-screen flex flex-col items-center">
  <%= render 'header',
            first_link: link_to('Meu Perfil', employer_path(current_employer)),
            second_link: button_to('Sair', destroy_employer_session_path, method: :delete) %>


  <main class="w-full xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-32">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <aside class="flex flex-col items-end mt-2" data-controller="dropdown">
      <button data-action="click->dropdown#toggle" aria-label="Menu" class="bg-green-500 hover:bg-green-600 text-white p-1 rounded-md">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </button>
      
      <section data-dropdown-target="menu" class="absolute flex flex-col hidden gap-4 p-4 mt-12 bg-white rounded-md shadow-lg">
        <%= link_to 'Editar vaga', edit_job_path(@job), class: 'bg-green-500 hover:bg-green-600 p-3 rounded-md text-white font-bold text-md' %>
        <%= button_to 'Excluir vaga', @job, method: :delete, class: 'bg-red-500 hover:bg-red-600 p-3 rounded-md text-white font-bold text-md' %>
      </section>
    </aside>
    
    <%= render 'job_information', job: @job %>
    
    <div class="mt-8">
      <%= link_to 'Ver candidaturas', applyers_job_path, class: 'bg-green-500 px-3 py-3 rounded-md hover:bg-green-600 text-white font-bold text-md' %>
    </div>
  </main>
  
  <div class="mt-8">
    <%= link_to 'Ir para Vagas', jobs_path, class: 'text-green-600 hover:bg-green-200  py-3 p-4 rounded-md text-md font-bold' %>
  </div>
</div>