config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#welcome'

  devise_for :job_seekers, controllers: {
    registrations: 'job_seekers/registrations'
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }

  resources :home do
    member do
      post 'apply'
    end
  end
  resources :job_seekers, only: %i[edit update destroy show] do
    member do
      get 'applys'
    end
  end

  resources :jobs do
    member do
      get :applyers
      get 'applyer/:job_seeker_id', to: 'jobs#applyer', as: :applyer
    end
  end
  resources :employers

  devise_scope :job_seeker do
    get '/job_seekers/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :employer do
    get '/employers/sign_out' => 'devise/sessions#destroy'
  end

  get 'start', to: 'home#index', as: :start
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_job_seeker!, except: :welcome
  before_action :verify_profile, only: :apply
  
  def welcome; end

  def index
    jobs = Job.all
    @jobs = jobs.sort_by(&:created_at).reverse
  end

  def show
    @job = Job.find(params[:id])
    @application = @job.applications.find_by(job_seeker_id: current_job_seeker.id)
  end

  def apply
    @job = Job.find(params[:id])
    @apply = @job.applications.create(job_seeker: current_job_seeker)

    if @apply.save
      redirect_to home_path(@job), notice: 'Candidatura enviada com sucesso!'
    else
      redirect_to home_path(@job), notice: 'Não foi possivel enviar sua candidatura'
    end
  end
  
  private
  
  def verify_profile
    if current_job_seeker.full_name == nil 
      redirect_to edit_job_seeker_path(current_job_seeker), notice: 'Complete seu perfil antes de continuar'
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_header.html.erb
<header class="bg-white shadow-lg w-full fixed top-0 left-0 z-40">
    <div class="w-11/12 mx-auto px-4 sm:px-6 lg:px-8">
      <nav class="flex items-center justify-between h-20 sm:h-24 xl:h-24 relative" data-controller="mobile-menu">

        <div class="flex-shrink-0 text-2xl sm:text-3xl xl:text-4xl font-extrabold text-green-600">
          <%= link_to 'Feira Vagas', start_path %>
        </div>

        <div class="lg:flex lg:items-center lg:space-x-4 md:hidden hidden">
          <div class="text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold">
            <%= first_link %>
          </div>

          <div class="text-red-600 hover:bg-red-200 px-4 py-2 rounded-md text-md font-bold">
            <%= second_link  %>
          </div>
        </div>

        <button data-action="click->mobile-menu#toggle" aria-label="Menu" class="block lg:hidden px-2 py-1 text-green-700 hover:bg-green-100 rounded-md">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>

        <div data-mobile-menu-target="menu" class="lg:hidden fixed inset-0 bg-white z-50 hidden transition-transform transform duration-300 ease-in-out">
          <div class="flex flex-col items-end px-4 py-8">
            <button data-action="click->mobile-menu#toggle" aria-label="Fechar Menu" class="self-end px-4 py-2 text-gray-700">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>

            <div class="flex flex-col items-end px-4"> 
              
              <div class="text-green-700 hover:bg-green-100 px-2 py-2 rounded-md text-md font-bold">
                <%= first_link %>
              </div>

              <div class="text-red-700 hover:bg-red-100 px-2 py-2 rounded-md text-md font-bold">
                <%= second_link  %>
              </div>

            </div>
          </div>
        </div>
      </nav>
    </div>
</header>

app/views/home/_job.html.erb
<div id="<%= dom_id(job) %>" class="transition-transform transform hover:scale-105">
  <!-- Job Header -->
  <div class="flex flex-row justify-between items-center mb-4">
    <div class="flex flex-row items-center gap-3">
      <% if job.employer.profile_img.attached? %>
        <div class="w-12 h-12 rounded-full bg-gray-200 flex items-center justify-center">
          <%= image_tag job.employer.profile_img, alt: "Foto de Perfil", class: "rounded-full object-cover w-full h-full" %>
        </div>
      <% end %>
      <p class="text-lg font-semibold text-green-700"><%= job.employer.company_name %></p>
    </div>
    <p class="text-sm text-gray-500"><%= job.created_at.strftime('%d/%m') %></p>
  </div>
  
  <!-- Job Title -->
  <div class="mb-4">
    <h2 class="text-xl font-bold text-gray-800"><%= job.title %></h2>
  </div>

  <!-- Job Details -->
  <div class="flex flex-col text-gray-600">
    <p class="mb-1"><strong>Localização:</strong> <%= job.location %></p>
    <p><strong>Modalidade:</strong> <%= job.mode %></p>
  </div>
</div>

app/views/home/_job_information.html.erb
<section class="mb-6">
  <h1 class="text-3xl font-bold text-gray-800 mb-5">
    <%= @job.title %>
  </h1>
  <div class="flex flex-row items-center gap-3">
    <% if @job.employer.profile_img.attached? %>
      <div class="w-12 h-12 rounded-full bg-gray-200 flex items-center justify-center">
        <%= image_tag @job.employer.profile_img, alt: "Foto de Perfil", class: "rounded-full object-cover w-full h-full" %>
      </div>
    <% end %>
  
    <h2 class="text-xl text-gray-600 mt-2">
      <%= @job.employer.company_name %>
    </h2>
  </div>
</section>


<section class="mb-8 grid grid-cols-1 lg:grid-cols-2 gap-6">
  <div class="space-y-4">
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Localização:</h3>
      <p class="text-gray-600"><%= @job.location %></p>
    </div>
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Salário:</h3>
      <p class="text-gray-600"><%= @job.salary %></p>
    </div>
  </div>
  <div class="space-y-4">
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Tipo de Contrato:</h3>
      <p class="text-gray-600"><%= @job.mode %></p>
    </div>
    <div>
      <h3 class="text-xl font-semibold text-gray-700">Data de Publicação:</h3>
      <p class="text-gray-600"><%= @job.created_at.strftime('%d/%m') %></p>
    </div>
  </div>
</section>

<section>
  <div class="pb-4" >
    <h3 class="text-xl font-semibold text-gray-700">Descrição da Vaga</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%= @job.description %></p>
  </div>
  
  <div class="pb-4">
    <h3 class="text-xl font-semibold text-gray-700">Requisitos</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%=@job.requirements %></p>
  </div>

  <div class="pb-4">
    <h3 class="text-xl font-semibold text-gray-700">Qualificações</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%= @job.skills %></p>
  </div>

  <div class="pb-4">
    <h3 class="text-xl font-semibold text-gray-700">Benefícios</h3>
    <p class="whitespace-pre-wrap text-gray-700"><%= @job.benefits %></p>
  </div>
</section>

<section class="flex flex-row justify-start mt-4">
  <% if @application&.status.eql?(false || nil) %>
    <%= button_to 'Candidate-se', apply_home_path(@job) , method: :post, class: 'bg-green-500 hover:bg-green-600 p-3 rounded-md text-white font-bold text-md' %>
  <% else %>
    <button class='bg-gray-500 hover:bg-gray-600 cursor-not-allowed p-3 rounded-md text-white font-bold text-md'>Candidatado</button>
  <% end %>
</section>

app/views/home/index.html.erb
<div class="container flex flex-col items-center justify-center mx-auto min-h-screen py-8">
  <%= render 'header',
              first_link: link_to('Meu Perfil', job_seeker_path(current_job_seeker)),
              second_link: button_to('Sair', destroy_job_seeker_session_path, method: :delete) 
  %>
  
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-100 mt-24 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  
  <main class="w-11/12 xl:w-full lg:px-8 mt-24 mx-auto grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-6">
    <% @jobs.each do |job| %>
      <%= link_to home_path(job), class: "md:transform md:hover:scale-105 transition-transform duration-200 ease-in-out" do %>
        <div class="bg-white overflow-hidden shadow-lg rounded-lg p-6">
          <%= render 'job', job: job %>
        </div>
      <% end %>
    <% end %>
  </main>
</div>

app/views/home/show.html.erb
<div class="container mx-auto min-h-screen flex flex-col items-center">
  <%= render 'header',
              first_link: link_to('Meu Perfil', job_seeker_path(current_job_seeker)),
              second_link: button_to('Sair', destroy_job_seeker_session_path, method: :delete) %>

  <main class="w-full xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-32">

    <%= render 'job_information', job: @job %>
  </main>

  <div class="max-lg:hidden mt-8">
    <%= link_to 'Voltar para Vagas', start_path, class: 'text-green-600 bg-green-200 hover:bg-green-300 py-3 p-4 rounded-md text-md font-bold' %>
  </div>
</div>

app/views/home/welcome.html.erb
<div  class="container flex flex-col items-center justify-center mx-auto min-h-screen py-8">
  <%= render 'header',
              first_link: link_to('Candidate-se', start_path),
              second_link: link_to('Contrate', jobs_path) 
  %>

  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-100 mt-24 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  
  <main class="flex flex-col items-center justify-center w-full px-4 sm:px-6 lg:px-8 mt-24 flex-1 text-center">
 
    <section>
      <h1 class="text-5xl font-extrabold text-green-700 mb-6">Bem-vindo ao Feira Vagas</h1>
      <p class="text-lg text-gray-700 mb-6">Conectando talentos e oportunidades em Feira de Santana.</p>
    </section>

    <section class="mb-12">
      <%= image_tag 'img.jpg', alt: 'Imagem de um homen negro, sorrindo e apontando para um telefone na sua esqueda, o telefone está navegando na página principal do site', class: 'w-full max-w-xl mx-auto' %>
    </section>

    <section>
      <div class="flex space-x-8">
        <%= link_to 'Candidatar-se', start_path, class: 'bg-green-700 hover:bg-green-600 text-white font-bold py-3 px-6 rounded-lg transition ease-in-out duration-150' %>
        <%= link_to 'Anunciar vaga', jobs_path, class: 'bg-red-700 hover:bg-red-600 text-white font-bold py-3 px-6 rounded-lg transition ease-in-out duration-150' %>
      </div>
    </section>
  </main>
</div>