config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#welcome'

  devise_for :job_seekers, controllers: {
    registrations: 'job_seekers/registrations'
  }
  devise_for :employers, controllers: {
    registrations: 'employers/registrations'
  }

  resources :home do
    member do
      post 'apply'
    end
  end
  resources :job_seekers, only: %i[edit update destroy show] do
    member do
      get 'applys'
    end
  end

  resources :jobs do
    member do
      get :applyers
      get 'applyer/:job_seeker_id', to: 'jobs#applyer', as: :applyer
    end
  end
  resources :employers

  devise_scope :job_seeker do
    get '/job_seekers/sign_out' => 'devise/sessions#destroy'
  end
  devise_scope :employer do
    get '/employers/sign_out' => 'devise/sessions#destroy'
  end

  get 'start', to: 'home#index', as: :start
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/employer.rb
# frozen_string_literal: true

class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validate :correct_profile_img_mime_type
  has_one_attached :profile_img
  has_many :jobs, dependent: :destroy
  
  private

  def correct_profile_img_mime_type
    if profile_img.attached? && !profile_img.content_type.in?(%w[image/jpeg image/png image/gif])
      errors.add(:profile_img, 'deve ser uma imagem JPG, PNG ou GIF')
    elsif profile_img.attached? && profile_img.byte_size > 5.megabytes
      errors.add(:profile_img, 'deve ser menor que 5MB')
    end
  end
end

app/controllers/employers/registrations_controller.rb
# frozen_string_literal: true

class Employers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |employer|
      if employer.persisted?
        sign_in(employer)
        redirect_to jobs_path
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super do |employer|
      if employer.destroyed?
        redirect_to root_path, notice: 'Sua conta foi excluida com sucesso. Você foi redirecionado para a pagina inicial'
        return
      end
    end
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: %i[ show edit update destroy ]
  before_action :authenticate_employer!

  def show; end

  def edit; end

  def update
    if @employer.update(employer_params)
      redirect_to employer_url(@employer), notice: 'Perfil atualizado com sucesso'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy 
    @employer.destroy
    redirect_to root_path
  end
  
  private

  def set_employer
    @employer = Employer.find(params[:id])
  end
  
  def employer_params 
    params.require(:employer).permit(%i[ company_name email location phone profile_img site ])
  end
end

app/helpers/employers_helper.rb
# frozen_string_literal: true

module EmployersHelper
end

app/views/employers/_employer_data.html.erb
<div class="flex flex-col items-center space-y-6">
  <div class="w-52 h-52 rounded-full bg-gray-200 flex items-center justify-center">
    <% if @employer.profile_img.attached? %>
      <%= image_tag @employer.profile_img, alt: "Foto de Perfil", class: "rounded-full object-cover w-full h-full" %>
    <% else %>
      <p>No image</p>
    <% end %>
  </div>
  
  <div class="text-center">
    <h2 class="text-2xl font-bold text-gray-800"><%= @employer.company_name %></h2>
    <p class="text-blue-800"><%= link_to @employer.site, "https://#{@employer.site}", target: "_blank" %></p>
  </div>
  
  <div class="w-full text-left my-8 space-y-4">
    <p class="text-gray-600"><strong>Email:</strong> <%= @employer.email %></p>
    <p class="text-gray-600"><strong>Tel:</strong> <%= @employer.phone %></p>
    <p class="text-gray-600"><strong>Cidade:</strong> <%= @employer.location %></p>
  </div>
</div>

app/views/employers/_form.html.erb
<%= form_with(model: @employer, local: true, class: "space-y-6") do |form| %>

  <div class="flex flex-col">
    <%= form.label :profile_img, "Foto de Perfil", class: "text-gray-700 font-bold mb-2" %>
    <%= form.file_field :profile_img, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600 cursor-pointer bg-white" %>
  </div>

  <div class="flex flex-col">
    <%= form.label :company_name, "Nome da empresa", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :company_name, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :email, "Email", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :email, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :site, "Site", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :site, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600" %>
  </div>
  
  <div class="flex flex-col">
    <%= form.label :phone, "Telefone", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_field :phone, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>

  <div class="flex flex-col">
    <%= form.label :location, "Localidade", class: "text-gray-700 font-bold mb-2" %>
    <%= form.text_area :location, class: "px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-600", required: true %>
  </div>
  
  <div class="text-center">
    <%= form.submit 'Editar Perfil', class: "bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-md font-bold cursor-pointer" %>
  </div>

<% end %>

app/views/employers/_header.html.erb
<header class="bg-white shadow-lg w-full fixed top-0 left-0 z-40">
    <div class="w-11/12 mx-auto px-4 sm:px-6 lg:px-8">
      <nav class="flex items-center justify-between h-20 sm:h-24 xl:h-24 relative" data-controller="mobile-menu">

        <div class="flex-shrink-0 text-2xl sm:text-3xl xl:text-4xl font-extrabold text-green-600">
          <%= link_to 'Feira Vagas', jobs_path %>
        </div>

        <div class="lg:flex lg:items-center lg:space-x-4 hidden md:hidden">
          <div class="text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold">
            <%= first_link %>
          </div>

          <div class="text-red-600 hover:bg-red-200 px-4 py-2 rounded-md text-md font-bold">
            <%= second_link  %>
          </div>
        </div>

        <button data-action="click->mobile-menu#toggle" aria-label="Menu" class="block lg:hidden px-2 py-1 text-green-700 hover:bg-green-100 rounded-md">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>

        <div data-mobile-menu-target="menu" class="lg:hidden fixed inset-0 bg-white z-50 hidden transition-transform transform duration-300 ease-in-out">
          <div class="flex flex-col items-end px-4 py-8">
            <button data-action="click->mobile-menu#toggle" aria-label="Fechar Menu" class="self-end px-4 py-2 text-gray-700">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>

            <div class="flex flex-col items-end px-4"> 
              
              <div class="text-green-700 hover:bg-green-100 px-2 py-2 rounded-md text-md font-bold">
                <%= first_link %>
              </div>

              <div class="text-red-700 hover:bg-red-100 px-2 py-2 rounded-md text-md font-bold">
                <%= second_link  %>
              </div>

            </div>
          </div>
        </div>
      </nav>
    </div>
</header>

app/views/employers/edit.html.erb
<div class="container flex flex-col mx-auto items-center justify-center min-h-screen py-8">
  <%= render 'header',
              first_link: link_to('Meu Perfil', employer_path, class: "text-green-600 hover:bg-green-200 px-4 py-2 rounded-md text-md font-bold"),
              second_link: button_to('Sair', destroy_employer_session_path, method: :delete, class: "text-red-600 hover:bg-red-200 px-4 rounded-md text-md font-bold") %>
  
  <main class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <%= render 'form', employer: @employer %>
  </main>

  <section class="mt-6 text-center">
    <%= link_to 'Voltar para vagas', jobs_path, class: "text-green-600 hover:underline py-3 px-4 rounded-md text-md font-bold" %>
  </section>
</div>

app/views/employers/show.html.erb
<div class=" container flex flex-col items-center justify-center mx-auto min-h-screen py-8">
  <%= render 'header',
          first_link: link_to('Suas vagas', jobs_path),
          second_link: button_to('Sair', destroy_employer_session_path, method: :delete)%>
  <div class="w-11/12 xl:w-3/4 bg-white shadow-lg rounded-lg p-8 mt-24">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 text-center font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    
    <%= render 'employer_data' %>

    <div class="mt-6 text-center flex flex-row justify-between">
      <%= link_to 'Editar Perfil', edit_employer_path, class: "text-white bg-green-600 hover:bg-green-700 px-6 py-2 rounded-md font-bold" %>
      <%= button_to 'Excluir Perfil', registration_path(current_employer), method: :delete, class: "text-white bg-red-600 hover:bg-red-700 px-6 py-2 rounded-md font-bold" %>
    </div>
  </div>
</div>